UniversityWebAPI/UniversityMVCWebApp/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using UniversityMVCWebApp.Areas.Identity.Data;
using UniversityMVCWebApp.Data;
using UniversityMVCWebApp.Models;

namespace UniversityMVCWebApp.Controllers
{
    [Authorize(policy: "readonlypolicy")]
    public class AdminController : Controller
    {
        private readonly UniversityMVCWebAppContext _universityMVCWebAppContext;
        private readonly UserManager<UniversityMVCWebAppUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public AdminController(UniversityMVCWebAppContext universityMVCWebAppContext, UserManager<UniversityMVCWebAppUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _universityMVCWebAppContext = universityMVCWebAppContext;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public ActionResult RegisterData()
        {
            return View();
            
        }
        public IActionResult Index()
        {
            if (_universityMVCWebAppContext.Approval == null)
            {
                return NotFound();
            }
            List<AdminViewModel> admins = new List<AdminViewModel>();
            admins = _universityMVCWebAppContext.Approval.ToList();
            if (admins == null)
            {
                return NotFound();
            }
            return View(admins);
        }
        [HttpPost]

        public async Task<IActionResult> Approval(int  id)
        {
            var data = _universityMVCWebAppContext.Approval.Find(id);
            if (data == null)
            {
                return NoContent();
            }

            var user = new UniversityMVCWebAppUser()
            {
               Email=data.Email,
                PanNumber = data.PanNumber,
                UserName = data.Email
            };
            var approval = new StatusViewModel()
            {
                //Id = data.Id,
                Email=data.Email,
                //PanNumber=data.PanNumber,   
                //Password=data.Password,
                //ConfirmPassword=data.ConfirmPassword,
                //RoleName=data.RoleName,
                Status = "Success"
            };
            _universityMVCWebAppContext.StatusViewModel.Add(approval);
            var roles = _roleManager.FindByNameAsync(data.RoleName).Result;
            await _userManager.CreateAsync(user, data.Password);
            await _userManager.AddToRoleAsync(user, roles.Name);
            _universityMVCWebAppContext.Approval.Remove(data);
            _universityMVCWebAppContext.SaveChanges();
            return Json("Success");




        }
        public async Task<IActionResult> Rejection(int id)
        {
            var data = _universityMVCWebAppContext.Approval.Find(id);
            if (data == null)
            {
                return NotFound();
            }
            _universityMVCWebAppContext.Approval.Remove(data);
            _universityMVCWebAppContext.SaveChanges();
            var reject = new StatusViewModel()
            {

                //Id = data.Id,
                Email = data.Email,
                //PanNumber = data.PanNumber,
                //Password = data.Password,
                //ConfirmPassword = data.ConfirmPassword,
                //RoleName = data.RoleName,
                Status = "Rejected"
            };
            _universityMVCWebAppContext.StatusViewModel.Add(reject);
            _universityMVCWebAppContext.Approval.Add(data);
            _universityMVCWebAppContext.SaveChanges();
            return Json("Rejected");





        }
    }
}
    

UniversityWebAPI/UniversityMVCWebApp/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace UniversityMVCWebApp.Controllers
{
    [Authorize(policy: "readonlypolicy")]
    public class RoleController : Controller
    {
        private RoleManager<IdentityRole> _roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var role = _roleManager.Roles.ToList();
            return View(role);
        }
        public IActionResult Create()
        {

            return View(new IdentityRole());
        }
        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            await _roleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }
    }
}

UniversityWebAPI/UniversityMVCWebApp/Controllers/UniversitiesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using UniversityMVCWebApp.APIModel;
using UniversityMVCWebApp.Models;
using UniversityMVCWebApp.Repository;

namespace UniversityMVCWebApp.Controllers
{
    
    public class UniversitiesController : Controller
    {
         Uri baseUri = new Uri("https://localhost:7168/api");
            HttpClient client = new HttpClient();

        List<UniversityViewModel> UniversityList = new List<UniversityViewModel>();
        //private readonly IDataRepository<UniversityModelApi> _universityDataRepository;
        private readonly IMapper _imapper;


        //public UniversitiesController(IDataRepository<UniversityModelApi> universityDataRepository)
        //{
        //    _universityDataRepository = universityDataRepository;
        //    
        //}
        public UniversitiesController(IMapper imapper)
        {
            _imapper = imapper;
        }




        //Details of  the universities
        public IActionResult Index()
            {
                client.BaseAddress = baseUri;
                HttpResponseMessage response = client.GetAsync(baseUri + "/University").Result;
                if (response.IsSuccessStatusCode)
                {
                    string UniversityData = response.Content.ReadAsStringAsync().Result;
                    UniversityList = JsonConvert.DeserializeObject<List<UniversityViewModel>>(UniversityData); ;

                }
                var result = UniversityList.OrderByDescending(e => e.establishedYear).ThenBy(e => e.universityName);
            
            _imapper.Map<UniversityModelApi>(result);
            return View(result);
            return View(UniversityList);
            IEnumerable<UniversityViewModel> university = (IEnumerable<UniversityViewModel>)_universityDataRepository.GetAll();

        }

        //Add the university details
        [Authorize(policy: "writepolicy")]
        public IActionResult Create()
        {

                return View();
        }
        [HttpPost]

            public ActionResult AddUniversity(UniversityViewModel university)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("https://localhost:7168/api/University");
                    var postTask = client.PostAsJsonAsync<UniversityViewModel>("University", university);
                    postTask.Wait();
                    var result = postTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                        //_universityDataRepository.Add(result);
                        // return RedirectToAction(actionName: nameof(Index));
                         //_imapper.Map<UniversityModelApi>(university);
                }
                    return View();
                    }

            }
        //Edit the university details
        [Authorize(policy: "writepolicy")]
        public ActionResult Edit(int id)
        {
                client.BaseAddress = baseUri;
                HttpResponseMessage response = client.GetAsync(baseUri + "/University").Result;
                string data = response.Content.ReadAsStringAsync().Result;
                UniversityList = JsonConvert.DeserializeObject<List<UniversityViewModel>>(data);
                var university = UniversityList.Where(e => e.id == id).FirstOrDefault();
                _imapper.Map<UniversityModelApi>(university);
                return View(university);
        }
        [HttpPost]
        public IActionResult Save(UniversityViewModel university)
        {
           using (var client = new HttpClient())
           {
                    client.BaseAddress = new Uri("https://localhost:7168/api/");
                    var put = client.PutAsJsonAsync($"University?id={university.id}", university);
                    put.Wait();
                    var result = put.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }

           }
           ModelState.AddModelError(string.Empty, "server error");
            
           return View();

        }
        [HttpDelete]
       // [Authorize(policy: "writepolicy")]
        public IActionResult Delete(int id)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("https://localhost:7168/api/University/");
                    var delete = client.DeleteAsync($"{id}");
                    delete.Wait();
                    var result = delete.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                }
                ModelState.AddModelError(string.Empty, "server error");
           // _imapper.Map<UniversityModelApi>(Results);
            return View();

        }
            


    }
}

UniversityWebAPI/UniversityMVCWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UniversityMVCWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UniversityMVCWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UniversityMVCWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Universities" asp-action="Index">Universities List</a>
                        </li>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Approval List</a>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial"/>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - UniversityMVCWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>